### ISSUE TITLE
centos7.5.1804 not tagged for ppc64le?

### ISSUE THREAD

**Issue by JonKohler** [docker-library/repo-info#27]
I noticed in https://github.com/docker-library/repo-info/blob/master/repos/centos/tag-details.md it looks like the 7.5.1804 tag is only for x86; however, if you drop the version number and either use centos:7 or centos:latest, it would work for ppc64le.

We have a use case were we compile on both x86 and ppc64le, and we're working on setting up a dockerfile. We'd love to pin the version, such that we're deterministically getting the same image for the rest of time, until such time we decide to pump it to "something else".

Just trying to prevent a future "why the heck is this working different today" pager beeper oncall.

Jon

**Comment by tianon** [comment]
The supported architectures are specified by the image maintainer in https://github.com/docker-library/official-images/blob/master/library/centos -- as you can see there, `centos:7.5.1804` is _not_ an alias for `centos:7`, but rather a point-in-time release build (which doesn't include any other arches currently).

I'd recommend filing an issue with the maintainer (since there's almost zero chance the maintainer of that image follows this purely-informational repository) so they can look into this and decide whether it's intentional or something they want to fix:

> -	**Where to file issues**:  
> 	[https://bugs.centos.org](https://bugs.centos.org) or [GitHub](https://github.com/CentOS/sig-cloud-instance-images/issues)
