### ISSUE TITLE
What exactly does this repository provide (for Apache Thrift)?

### ISSUE THREAD

**Issue by jeking3** [docker-library/repo-info#30]
In the container (part of this repository repo-info/repos/thrift/) I can see that it provides the thrift compiler in /usr/local/bin/thrift, but that's all I could find.  Is that all that it is supposed to provide?  The official curated docker page README isn't very specific about it.

**Comment by wglambert** [comment]
Are you looking for https://github.com/ahawkins/docker-thrift

This repo is for extended information and artifacts on the built images

**Comment by jeking3** [comment]
Does anything from the official container source from the canonical home for Apache Thrift on Github or is it all provided in other ways?  How did you find https://github.com/ahawkins/docker-thrift from the information in repos/thrift ?

**Comment by wglambert** [comment]
https://hub.docker.com/_/thrift/
Under the "Where to file issues"

This is the Dockerfile https://github.com/ahawkins/docker-thrift/blob/master/0.11/Dockerfile
And it's downloaded from apache:
`&& curl -sSL "http://apache.mirrors.spacedump.net/thrift/$THRIFT_VERSION/thrift-$THRIFT_VERSION.tar.gz" -o thrift.tar.gz \`

**Comment by tianon** [comment]
See also https://github.com/docker-library/official-images/blob/master/library/thrift, which is the canonical source-of-truth for what we build/push to the `thrift` repository namespace (which I'd mirror again my comment from https://github.com/ahawkins/docker-thrift/issues/12 that we'd be thrilled if it were actually upstream supported and/or maintained).

Closing this, since there isn't anything actionable here for the https://github.com/docker-library/repo-info repository (feel free to continue discussing here, but be aware that the discussion might get lost).
