### ISSUE TITLE
remote.sh missing info with some new windowsservercore images

### ISSUE THREAD

**Issue by spyoungtech** [docker-library/repo-info#45]
For example: [repos/python/remote/3.10.0b4-windowsservercore-1809.md](https://github.com/docker-library/repo-info/blob/b06e82e8e7c77efc2373d90f50ef292bbe806ea1/repos/python/remote/3.10.0b4-windowsservercore-1809.md) is missing all the platform and layer information.

Is this expected?

**Comment by tianon** [comment]
Looks like this was due to the blip we had with our Windows box and the image not being built yet -- if you look at the latest (https://github.com/docker-library/repo-info/blob/ff590fa901f2d8353a165aca54853bc09b73d2cf/repos/python/remote/3.10.0b4-windowsservercore-1809.md) it is full now.

I guess we probably should update `remote.sh` to handle an empty manifest list more reasonably. :sweat_smile:
