### ISSUE TITLE
The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.

### ISSUE THREAD

**Issue by Deepthi2305** [docker-library/repo-info#46]
We are pulling debian:stable-slim for our gitlab containers and while building the image it throws the below error

_+ DEBIAN_FRONTEND=noninteractive apt-get update -qq
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 100
ERROR: Job failed: exit code 1_

We have tried to pull  debian:stable but the same error.
Can you help fix it?

**Comment by wglambert** [comment]
https://github.com/docker-library/repo-info#readme
>This repository includes a set of scripts for generating reports of extended information about published official image repositories.

Not sure which image you're trying to build but it sounds like you need to do an `apt update` first to populate the `/var/lib/apt/lists/*`, any reason your building the image yourself instead of making a derivative Dockerfile with `FROM image`?

Going to close however since this isn't the right place and there isn't enough information to go by
You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by tianon** [comment]
https://github.com/debuerreotype/docker-debian-artifacts/issues/135 :eyes:
