### ISSUE TITLE
Oracle Cloud Ampere instance

### ISSUE THREAD

**Issue by megvadulthangya** [docker-library/repo-info#68]
Hi!

I get[ this](https://imgur.com/DwnnwBq) error when i paste this(not exactly this, i changed passwd) config into portainer:

version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

**Comment by wglambert** [comment]
The Joomla image is maintained over at https://github.com/joomla/docker-joomla
https://hub.docker.com/_/joomla
This repo is "Extended information (especially license and layer details) about the published Official Images"

To your error "failed to deploy a stack: joomladb no matching manifest for linux/arm64/v8 in the manifest list entires" it's because your service `joomladb` is using the image `mysql:5.6` which doesn't have arm64v8 variants because Oracle doesn't publish them. https://github.com/docker-library/mysql/pull/680#issuecomment-1044511070
See also https://github.com/docker-library/mysql/issues/905#issuecomment-1212477340
Also mysql:5.6 is EOL as of Feb 28 2021

**Comment by megvadulthangya** [comment]
Thank you for your time... Honestly i dont know how am i get here...
